#!/bin/bash
#Lets Encrypt
if [ -z "$DOMAIN" ]; then
	echo "You need the \$DOMAIN variable";
else
# lets move those certificates from mounted share
	echo "Requesting certificate"
	rm -rf /etc/letsencypt && \
	certbot certonly --webroot -w /usr/share/fusiondirectory/html -d $DOMAIN --email $GIT_EMAIL --agree-tos --quiet && \
		mkdir -p /var/www/html/certs && \
		cp -r /etc/letsencrypt/ /var/www/html/certs && \
		cp /var/www/html/certs/letsencrypt/live/${DOMAIN}/fullchain.pem /var/www/html/certs/cert.pem && \
		cp /var/www/html/certs/letsencrypt/live/${DOMAIN}/privkey.pem /var/www/html/certs/key.pem && \
		sed -i "s@#@@g" /etc/nginx/sites-available/default && \
		service nginx reload
fi
